### ISSUE TITLE
The GeoJSON for Uruguay is wrong

### ISSUE THREAD

**Issue by guillermodangelo** [microsoft/SouthAmericaBuildingFootprints#2]
It weights less than a megabyte, and has a very small number of geometries:
https://minedbuildings.blob.core.windows.net/southamerica/Uruguay.geojsonl.zip

**Comment by guillermodangelo** [comment]
Sorry, I misinterpreted the data.

**Comment by sumanttyagi** [comment]
@guillermodangelo was there a shift in data points ?
